### ISSUE TITLE
Stefan: Please provide names of running pipelines to stakeholders

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/Infrastructure#2]
Create AL request and response event. Handle events accordingly.

**Comment by eichelbe** [comment]
Notify @npav @ap0n about new protocol.

**Comment by eichelbe** [comment]
@npav @ap0n @PatrickSie @cuiqin enhancement request implemented, protocol changed in 0.5.0-SNAPSHOT (also protocol version changed). Requires infrastructure update for external service/QM-IConf, however QM-IConf is in release process so update here will happen later. If not already done, external service shall relay on DispatchAdapter rather than IDispatcher so that changes to the protocol do not directly impact code.

**Comment by ap0n** [comment]
This simply means (at least for the external service) replacing
```public class Dispatcher implements IDispatcher```
with
```public class Dispatcher extends DispatcherAdapter```
right?

**Comment by eichelbe** [comment]
Right.
