### ISSUE TITLE
Integrate reflective traces

### ISSUE THREAD

**Issue by eichelbe** [QualiMaster/Infrastructure#20]
Andrea:
Monitoring log -> eu.qualimaster.monitoring.tracing.ReflectiveFileTrace.java
Adaptation log ->
eu.qualimaster.adaptation.internal.AdaptationLoggerFile.java

**Comment by eichelbe** [comment]
Integrating into adaptation layer/monitoring layer

**Comment by eichelbe** [comment]
preliminary integration:

 - AdaptationLayer writes to <adaptation.log.reflective.location>/reflective.log
 - MonitoringLayer writes to <monitoring.logInfra.location>/<yyyyMMdd-HHmmss>.rtrace using the point in time the infrastructure started. We may also change this to a fixed name, i.e., a file that is overridden if the infrastructure starts.

@cuiqin could you please set adaptation.log.reflective.location on all clusters to monitoring.logInfra.location, just for the beginning...

**Comment by eichelbe** [comment]
ok, Jenkins is building...
@cuiqin please close if setup change is done. thanks.

**Comment by cuiqin** [comment]
The required setting is done
